### ISSUE TITLE
 Invalid byte sequence for encoding

### ISSUE THREAD

**Issue by kpettijohn** [esripdx/rainman#16]
We are seeing the following byte sequence error on each Rainmaker run. The following log is from the rainman API server.

```
E, [2015-03-03T22:46:02.265896 #6443] ERROR -- : PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xe7 0x6f: EXECUTE update_stat; [9, "safasd723esef", "qwersdafa22", "2015-02-07", "name", "abcd servi\xE7o"]
```

**Comment by aaronpk** [comment]
oh no I thought I fixed this already...

**Comment by JerrySievert** [comment]
oh noes. the backup?

**Comment by JerrySievert** [comment]
did it get deployed?

**Comment by aaronpk** [comment]
hmm I fixed it on the Geotrigger server side: https://github.com/ArcGIS/Geotrigger-Server/issues/396

**Comment by aaronpk** [comment]
oh nevermind this is totally different. This is Postgres complaining about it!

**Comment by aaronpk** [comment]
This is the best thread I've seen on this problem: http://stackoverflow.com/questions/19712889/postgres-encoding-error-in-sidekiq-app

It boils down to:
* There are some byte sequences that are not valid UTF-8 characters
* A non-UTF-8 byte sequence such as `\xe8` may be interpreted as two different characters depending on the original encoding (è in ISO-8859-1 and č in ISO-8859-2)

Therefore we have no way to actually know what the invalid characters should be. We can either remove/replace the characters, or just not process that row.

I was not able to get this to actually replace the characters:

```
"abcd servi\xE7o".encode("UTF-8", :invalid => :replace, :undef => :replace, :replace => "?")
```

so I suggest we just avoid processing the record instead, which we can check with:

```
"abcd servi\xE7o".valid_encoding? => false
```

**Comment by aaronpk** [comment]
Decided to remove the invalid chars instead, using the "scrub_rb" gem.
